apiVersion: v1
kind: Namespace
metadata:
  name: ebdn
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: ebdn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: ebdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: quay.io/ebeaudoi/httpd-24:latest
        name: webserver
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: ebdn
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: webserver
